### ISSUE TITLE
이미지를 웹에서 복사하여 게시물에 붙여넣기 했을 때 게시물이 제출되지 않음.

### ISSUE THREAD

**Issue by WonGyuKim** [coms-server/server-issue#10]
![image](https://user-images.githubusercontent.com/28239997/97453924-8bac6380-1979-11eb-9e5d-522882586c3b.png)
구글에서 위와 같은 이미지를 검색하여 복사 + 게시물 작성에서 붙여넣기를 했는데 게시물 제출이 되지 않습니다.

**Comment by SnowlyFeast** [comment]
중복이슈
