### ISSUE TITLE
게시물 수정 버튼 눌렀을 때 수정 창에서 원본 제목 중 첫 번째 띄어쓰기까지만 나타납니다.

### ISSUE THREAD

**Issue by WonGyuKim** [coms-server/server-issue#11]
다음은 예시 화면입니다.

![image](https://user-images.githubusercontent.com/28239997/97454461-2311b680-197a-11eb-962a-0b9e419a187a.png)
위와 같은 상태에서 '수정' 버튼을 눌러서 게시물을 수정하려 하면

![image](https://user-images.githubusercontent.com/28239997/97454552-3c1a6780-197a-11eb-8d15-6de43518682c.png)
제목이 첫 어절까지만 출력되고 그 뒤는 사라집니다.

**Comment by SnowlyFeast** [comment]
중복이슈
