### ISSUE TITLE
디자인 수정

### ISSUE THREAD

**Issue by SnowlyFeast** [coms-server/server-issue#13]
editor에서 attachment 부분

기존글 수정에서 첨부파일 수정시 보이는 텍스트랑 첨부파일 요소가 너무 밋밋하니 조금만 예쁘게 다듬어주셈

**Comment by SnowlyFeast** [comment]
+ 투표에서 0 아래로는 빨간색으로, 0 이상으로는 초록색으로 색상 바뀌게 해주셈

자신이 투표한 것 만큼 진한색 말고 연한색으로

**Comment by SnowlyFeast** [comment]
qna 게시판에서 답변간 새로운 영역을 할당받아 서로 구분 됐으면 좋겠음.
------------------------------------------------------------------------------


직접 해결함

**Comment by grayroom** [comment]
> editor에서 attachment 부분
> 기존글 수정에서 첨부파일 수정시 보이는 텍스트랑 첨부파일 요소가 너무 밋밋하니 조금만 예쁘게 다듬어주셈

이건 일단 editor의 underbar와 attachment-container를 분리했음. 더 개선사항이 필요하다면, 추가바람

**Comment by grayroom** [comment]
> 투표에서 0 아래로는 빨간색으로, 0 이상으로는 초록색으로 색상 바뀌게 해주셈
> 자신이 투표한 것 만큼 진한색 말고 연한색으로

수정됨

**Comment by grayroom** [comment]
> > editor에서 attachment 부분
> > 기존글 수정에서 첨부파일 수정시 보이는 텍스트랑 첨부파일 요소가 너무 밋밋하니 조금만 예쁘게 다듬어주셈
> 
> 이건 일단 editor의 underbar와 attachment-container를 분리했음. 더 개선사항이 필요하다면, 추가바람

![image](https://user-images.githubusercontent.com/43588644/99267032-c4e43f00-2866-11eb-96c1-ab5aa2c7b300.png)
어 너무 안예쁜데 현재시각 23시 52분인 관계로 추후에 다듬어서 커밋하겠음

**Comment by grayroom** [comment]
이번 [커밋](https://github.com/SnowlyFeast/Coms-Server/commit/0b3f71f6d636c2e1e2a0fa2c6e31a4070395111b)에서 수정된 사항
1. noti 팝업 애니메이션 추가
2. 첨부파일/underbar 분리
3. hover시 bold로 강조되는것 애니메이션 추가
4. 모바일 뷰 sidebar(header)에 불필요한 공간 삭제

이외에 몇가지 수정사항은 직접 커밋로그 확인바람. 검증도 한번 해주길 바람.

**Comment by SnowlyFeast** [comment]
확인완
