### ISSUE TITLE
모바일에서 컨텍스트 메뉴가 안열림

### ISSUE THREAD

**Issue by SnowlyFeast** [coms-server/server-issue#17]
ㅈㄱㄴ

**Comment by grayroom** [comment]
https://github.com/SnowlyFeast/Coms-Server/commit/feb1966c57dac3cee9a93f450051debc2e187ca2#r44221698

따라서, 기존 js 코드의 선택자(.sidebar)를 (#sidebar)로 변경하여 해당버그 수정하였음.
