### ISSUE TITLE
투표 안됨

### ISSUE THREAD

**Issue by SnowlyFeast** [coms-server/server-issue#18]
ㅈㄱㄴ

+게시글 목록에서 투표 수가 보이면 좋겠음

**Comment by grayroom** [comment]
https://github.com/coms-server/coms/blob/9fb139f097d62dd9b9b28705d8c5c4596cb374a5/src/main/webapp/WEB-INF/jsp/layout/frag_quill_reader.jsp#L92-L100

해당 코드가 이후 버전에서 사라져서 생긴 문제로 보임. 수정바람.

**Comment by grayroom** [comment]
수정완료됨
