### ISSUE TITLE
이미지 업로드 안됨 

### ISSUE THREAD

**Issue by EricSamuelJun** [coms-server/server-issue#19]
![image](https://user-images.githubusercontent.com/10573900/98918365-e1077980-2510-11eb-926f-7fbb2bdde585.png)
![image](https://user-images.githubusercontent.com/10573900/98918380-e49b0080-2510-11eb-8368-d372c630bf87.png)
이미지 업로드가 안됨
사진 추가 버튼으로 글 올림. 자유게시판이랑 게임게시판 둘다 있음 Q&A 게시판 확인안함

**Comment by grayroom** [comment]
수정되었음
