### ISSUE TITLE
관리자도구를 index페이지 내에 통합하면 좋을것 같음

### ISSUE THREAD

**Issue by grayroom** [coms-server/server-issue#20]
별도 창을 띄우다보니 창 전환이 페이지 이용에 방해가됨. 테스트 서버를 만들어서(아니면 현재 진행중인 베타를 잠시 종료하고 일정 조율하여 진행해도 좋을듯) css 충돌나는 해당 빌드를 올려주면 충돌되는 부분 확인 후 수정하여 통합하겠음.

**Comment by SnowlyFeast** [comment]
부트스트랩 자체의 문제라서 부트스트랩 css 수정하거나 우리 css를 셀렉터로 하나하나 지정하고 스타일 값 채워넣어야하는데 그정도 노가다가 필요하다고 생각 안함.
관리자도구가 일반 사용자에게 노출되는 것도 아니고 임원단이 만지는건데 예쁜 것보다 실용성이 문제.
index안에 꾸겨넣으면 창 좁아져서 가독성 박살남.

**Comment by grayroom** [comment]
bootstrap nav이용하여 select menu개선하였고, index내부에 통합해도 가독성도 문제 없다고 판단되어 통합하였음
