### ISSUE TITLE
ToastUI를 도입하는건에 대하여

### ISSUE THREAD

**Issue by grayroom** [coms-server/server-issue#21]
pagination / tree / Editor / Grid 등의 어플리케이션이 완성도가 괜찮아보임. 깔끔하기도 하고. 일단 toast-ui브랜치에서 작업해 볼 예정.

**Comment by SnowlyFeast** [comment]
토스트 ui를 어디에 적용할지 계획 있음?

**Comment by grayroom** [comment]
일단 관리자툴, 명부에 grid / 에디터, 페이징, FTP에 써보려구요

**Comment by grayroom** [comment]
필요성이 딱히 없는 것 같음... 폐기
