### ISSUE TITLE
회원가입신청후 어드민에게 noti를 날려주면 좋을 것 같음

### ISSUE THREAD

**Issue by grayroom** [coms-server/server-issue#25]
noti는 기본적으로 날려주고, email을 발송하는것도 검토 해볼것

**Comment by SnowlyFeast** [comment]
일단 접수

**Comment by SnowlyFeast** [comment]
댓글 노티 날리는 로직 수정하면서 얘도 같이 손보는걸로.

다음 빌드 수정 대상.

**Comment by grayroom** [comment]
추가하는김에 승인된 경우, 가입신청넣은 회원에게 이메일 알림을 보내는기능도 구현하면 좋을 것 같음

**Comment by grayroom** [comment]
가입신청시에 executive목록에 있는 인원들에게 noti가 전송되고, 승인/거부시 noti가 일괄 삭제되도록 구현됨
