### ISSUE TITLE
bootstrap 충돌 해결

### ISSUE THREAD

**Issue by grayroom** [coms-server/server-issue#28]
button 요소는 bootstrap전용으로 사용하고 그 외에는 input[type="button"]을 사용해야 할 듯

**Comment by SnowlyFeast** [comment]
무슨 말인지 모르겠으니 코드+예시 첨부 바람. 어디서 발생하는 이슈인지도.

**Comment by SnowlyFeast** [comment]
확인. 앞으로 작성 시 스타일시트에 유의하여 디자인 요소 사용할 것.
근데 디자인 너가 하잖아ㅋ
