### ISSUE TITLE
index에 노출된 게시글 중 공지글은 bold처리

### ISSUE THREAD

**Issue by SnowlyFeast** [coms-server/server-issue#31]
하면 좋겠다 라는 김수현님의 의견입니다.

자유롭게 토론해주세요.

**Comment by grayroom** [comment]
![image](https://user-images.githubusercontent.com/43588644/108724061-40414500-7568-11eb-8f1f-c23b5cfb61a0.png)


볼드처리보다는 디자인 통일성을 위해서 게시판에서 공지글 좌측에 빨간마킹 하는것 처럼 index에서도 빨간마킹 하도록 바꾸는게 좋을듯? (이미지 참조)

**Comment by grayroom** [comment]
위와같이 구현됨

**Comment by SnowlyFeast** [comment]
반영할 때 지시좀 받고 반영해. 기능 막 박지 말라고 몇 번 이야기함.
토론하라고 열어놨더니 이래 만들었음 하고 닫으면 어캄

**Comment by SnowlyFeast** [comment]
근데 일단 디자인 자체는 반대 안하니까 반영하되 이야기 나오면 지시 받고 닫으셈.
