### ISSUE TITLE
댓글 notification 로직 강화

### ISSUE THREAD

**Issue by SnowlyFeast** [coms-server/server-issue#33]
-한 게시글에 대한 댓글 noti 통합. (답글에 대한 noti는 개별로 유지)
-삭제된 댓글에 대한 noti 핸들.

구현하면서 회원가입에 대한 noti 로직도 같이 손 볼 것.

**Comment by grayroom** [comment]
한 게시글에 대한 댓글 noti를 통합하라는게 무슨 말인지 잘 모르겠습니다. 좀 더 자세히 명세해주세요.

**Comment by SnowlyFeast** [comment]
한 글에 댓글이 5개 달려도 알림 하나만 푸시할거라고ㅇ

**Comment by grayroom** [comment]
notiVO자체를 뜯어야 할 것 같아서 따로 논의하시죵

**Comment by grayroom** [comment]
기능개발중 DB수정이 필요한 경우가 종종 발생할 것 같은데, 개발용DB를 따로 만드는게 좋을 것 같아요
