### ISSUE TITLE
가입 신청시 확인 알람 요청

### ISSUE THREAD

**Issue by skyblue-bear** [coms-server/server-issue#35]
가입에 성공하여 인증을 기다린다는 등의 메세지가 포함되어
가입 신청이 제대로 전달됐는지 확인 가능한 알람등의 피드백을 요청

**Comment by SnowlyFeast** [comment]
원래 회원가입에 성공하면 성공적으로 요청을 보냈다는 메세지가 뜬 다음 메인페이지로 리다이렉션 되는데, 리다이렉션이 너무 빨라서 그런 것 같습니다.
확인 버튼 누르면 리다이렉션 하거나 타이머를 늘리는 등의 조치를 하겠습니다.

**Comment by grayroom** [comment]
개발버전에서 개선되었습니다. 다음 배포에 포함될 예정입니다.
