### ISSUE TITLE
서버 시간대 변경

### ISSUE THREAD

**Issue by mirusu400** [coms-server/server-issue#36]
지금 테스트로 글써보니 GMT+0 시간대로 글이 써지는데 서버시간대를 한국시간 (GMT+9) 로 바꾸면 좋을것 같습니다~~~
![Screenshot_20210221-210301_Chrome.jpg](https://user-images.githubusercontent.com/25397908/108624474-8a52f980-7488-11eb-92c4-f8af12ef95f1.jpg)

**Comment by SnowlyFeast** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
이거 정훈이가 서버타임 고쳤다했는데 다시 이러네요. 확인하겠습니다.

**Comment by grayroom** [comment]
서버타임을 KST로 바꾸긴 했는데, MariaDB내부 timezone이 GMT +0이에요... 권한을 받아서 수정해야 하는데, 이건 김수현에게 부탁하겠습니다. @RapidWorkers

**Comment by RapidWorkers** [comment]
완료
기존 데이터 수정도 완료

**Comment by SnowlyFeast** [comment]
닫겠습니다
