### ISSUE TITLE
프로필 수정시 제출은 되지만 반응없음 및 줄바꿈처리 필요

### ISSUE THREAD

**Issue by SnowlyFeast** [coms-server/server-issue#44]
제출은 되어서 새로고침시 반영은 되지만 일단 확인 버튼에 대한 반응이 없음.
모바일 크롬 기준.

또 자기소개란 줄바꿈문자 처리가 안되어서 줄바꿈이 안됨.
`<pre>` 태그 혹은 이랑 비슷한 역할을 하는거 적용하되, db로 들어가는 텍스트를 건들지 말것.(db값 바꾸면 다시 수정할 때 문제생김)
얘도 모바일 크롬 기준.

Pc환경 멀쩡한지 확인 부탁.

**Comment by SnowlyFeast** [comment]
수정완. 배포대기중

**Comment by grayroom** [comment]
1.0.10에서 수정 배포됨

**Comment by grayroom** [comment]
1.0.10에서 수정 배포됨

**Comment by SnowlyFeast** [comment]
프로필 줄바꿈 처리 안됨

**Comment by SnowlyFeast** [comment]
+제출버튼 누르고 새로고침이 아직안댐

**Comment by grayroom** [comment]
이번엔 정말 수정되었습니다. 확인해주세요
