### ISSUE TITLE
프로필 변경시 오류 발생

### ISSUE THREAD

**Issue by mijien0179** [coms-server/server-issue#47]
![image](https://user-images.githubusercontent.com/40613626/109834001-18975e80-7c85-11eb-8d5a-7feb5559e0c6.png)

프로필 사진을 변경할 때 오류가 발생하네요. 이 오류 때문에 혹시 refresh가 안되는게 아닌가 싶기도 하고.. refresh 기능이 없으면 추가해도 좋을 것 같습니다.

추가로 개인정보(연락처 등) 변경시에 저장 버튼을 누르려 할때 문제가 발생합니다.
![image](https://user-images.githubusercontent.com/40613626/109834230-4ed4de00-7c85-11eb-9a9b-b00abb7e0f17.png)

동일 이슈인것같네요

**Comment by grayroom** [comment]
저건 js 임포팅 문제네요 수정 해 놓겠습니다.

**Comment by grayroom** [comment]
브라우저 데이터 초기화 하고 다시 접속후에 동일 오류 발생하는지 확인해주세요... 저는 확인 불가하네요

**Comment by mijien0179** [comment]
변경 정상적으로 되네요
