### ISSUE TITLE
가입신청넣은 회원에게 승인/거부 알림기능 구현

### ISSUE THREAD

**Issue by grayroom** [coms-server/server-issue#48]
추가하는김에 승인된 경우, 가입신청넣은 회원에게 이메일 알림을 보내는기능도 구현하면 좋을 것 같음

_Originally posted by @grayroom in https://github.com/coms-server/server-issue/issues/25#issuecomment-783430666_

**Comment by SnowlyFeast** [comment]
??? 승인 거부 순간 계정이 날아가는데 뭘 날려.
승인된 회원한테만 메일 보내면 되는데 동아리 dns는 spf가 안되서 못보냄
