### ISSUE TITLE
임원 및 관리자의 회원 상태 제어 기능

### ISSUE THREAD

**Issue by RapidWorkers** [coms-server/server-issue#49]
임원 및 관리자의 회원 상태 제어 기능

재학생 -> 졸업생
재학생 <->휴학생

변경이 가능할 수 있도록...

**Comment by grayroom** [comment]
기능 추가했으며, 회원 관리도구 UI가 변경되었습니다. 다음 배포때 포함될 예정입니다.

**Comment by grayroom** [comment]
1.0.16빌드에 포함되어 배포되었습니다.
