### ISSUE TITLE
내용물이 비어있는 게시글의 작성시 오류창이 보이지 않음

### ISSUE THREAD

**Issue by RapidWorkers** [coms-server/server-issue#50]
내용물이 비어있는 게시글의 작성시 오류창이 보이지 않음

모바일에서 - 화면 회전하면 보임
데스크탑 - 안보임

**Comment by RapidWorkers** [comment]
![Uploading 0EFBFA60-FA0D-4846-82E3-ED8BA6239B40.png…]()

**Comment by RapidWorkers** [comment]
![96DC3241-AD03-488E-B427-D7F640A6D55B](https://user-images.githubusercontent.com/6492071/111118101-b525fe80-85ab-11eb-95b9-42cec9b82fc5.png)

**Comment by grayroom** [comment]
수정되었습니다. 감사합니다.
