### ISSUE TITLE
동아리 질문 글 수정 누르면 404로 연결됨

### ISSUE THREAD

**Issue by goodann** [coms-server/server-issue#51]
삭제도안됨

**Comment by grayroom** [comment]
@SnowlyFeast ArticleTools의 isAuthorized메서드에 오류가 있었습니다.

```java
if(user.isAdmin() || article.getUser_idx() == user.getUser_idx()) 
    return true;
else
    return false;
```
해당 메서드에서는 위와 같이 글 작성자와 현재 로그인된 유저의 고유 인덱스를 비교하여 글 수정 권한이 있는지 검증하게 되는데, 비교하려는 두 인덱스가 int가 아닌 Integer객체이므로, ==연산자 대신 .equals()메서드를 사용하는것이 적합합니다.

따라서 아래와 같이 로직을 수정했습니다.
```java
if(user.isAdmin() || article.getUser_idx().equals(user.getUser_idx())) 
    return true;
else
    return false;
```

수정하는 중에 댓글 수정하는 부분에도 같은 로직이 있어 동일하게 수정했습니다.

어드민 계정으로만 테스트를 진행하다보니 미처 확인하지 못했던 것 같습니다... 비슷한 로직이 또 있을지도 모르니 한번 점검해보는것이 좋을 듯 합니다.
