### ISSUE TITLE
회원정보의 link 및 mailto: 오동작

### ISSUE THREAD

**Issue by amwkr** [coms-server/server-issue#52]
#### 예시
입력된 링크 주소가 **test.kw.ac.kr** 일경우 실제 연결은 다음과 같은 주소로 진행됩니다.
https://coms.kw.ac.kr/mypage/test.kw.ac.kr
#### 원인
a 태그에 http://, https://, / 등을 붙여주지 않는 경우 현재 경로를 기준으로 이동합니다.
#### 해결 방안
- 링크 등록 과정에서 http:// 강제화
- 링크 문자열 내 https:// 여부에 따라 https:// 자동 추가

#### 예시
```html
<span><a href="mailto:" + test@kw.ac.kr>
        test@kw.ac.kr
</a></span>
```

**Comment by grayroom** [comment]
두 문제 모두 해결되었습니다.
링크는 기본적으로 http://를 앞에 붙여서 이동하도록 구현되었습니다.
