### ISSUE TITLE
브루트포스 방지 대책이 마련이 되어있는지

### ISSUE THREAD

**Issue by mijien0179** [coms-server/server-issue#53]
저는 일단 다른 사이트랑 다른 비번 사용해서 상관이 없긴 한데 혹시라도 같은 비밀번호 사용하는 분이 계시면 문제가 될 것 같네요.

**Comment by SnowlyFeast** [comment]
음...보안옵션이라 딱히 언급하고 싶지는 않은데 답장 읽으면 삭제함.
bcrypt함수를 쓰고있고 얘는 연산 횟수만 늘리면 연산이 오래걸리기 때문에 어느정도 무작위 대입에 안정성을 보장함.
그리고 랜덤 솔트가 붙어있어서 타 사이트db에서 비번 해시값이 유출되어도 비교도 못하거니와 솔트 때문에 사전공격도 안됨.
