### ISSUE TITLE
커뮤니티 그룹에 프로그래밍 관련 게시판이 생겼으면 좋겠습니다

### ISSUE THREAD

**Issue by mirusu400** [coms-server/server-issue#54]
지금 커뮤니티에 자유게시판 / 게임 2개의 게시판밖에 없는데

프로그래밍 관련 게시물을 쓰고싶어도 QnA 말고는 쓸곳이 없어보입니다.

커뮤니티 그룹에 프로그래밍 / 컴퓨터 관련 게시판 추가 건의해봅니당

**Comment by grayroom** [comment]
PS를 즐겨하는 저로서도 좋은생각인듯 합니다.

다만, 관리자가 휴가통제가 풀리기 전 까지는 개발이 쉽지가 않습니다😢 여러 개발소요가 있기도 하고, 단순 게시판 추가만으로는 부족하다는 생각이 들어 추가할 기능등을 구상한 뒤 추후 업데이트에 반영할 수있도록 하겠습니다.
