### ISSUE TITLE
인증서 기간 만료

### ISSUE THREAD

**Issue by mirusu400** [coms-server/server-issue#59]
![image](https://user-images.githubusercontent.com/25397908/130392302-62f356e6-8e1d-4911-91ea-3d10e8f51b36.png)

됐다고 나오네요
Let's encrypt 는 자동갱신 지원되니까 이거 설정해도 좋을거 같습니다

**Comment by RapidWorkers** [comment]
크론탭 스케쥴러 다시 확인하도록 하겠습니다.

**Comment by RapidWorkers** [comment]
자동으로 renew는 진행되나 nginx가 reload되지 않는 문제 확인
0825 Fix완료
