### ISSUE TITLE
인스타그램 링크 추가

### ISSUE THREAD

**Issue by RapidWorkers** [coms-server/server-issue#60]
계정 kwcoms

**Comment by grayroom** [comment]
![image](https://user-images.githubusercontent.com/43588644/148968197-8e86fdd1-24cb-4f43-bded-81448dbf54a6.png)

인스타그램 링크 추가하고, 깃허브 이슈 링크도 위치 수정했습니다. 다음 배포때 수정된 버전으로 배포하겠습니다.

**Comment by grayroom** [comment]
1.0.16빌드에 포함되어 배포되었습니다.
