### ISSUE TITLE
답변으로 단 게시글이 상위 게시글로 나오는 이슈 

### ISSUE THREAD

**Issue by cacaru** [coms-server/server-issue#7]
![image](https://user-images.githubusercontent.com/37200850/95605579-1e04ca00-0a94-11eb-86f9-90f34bfc1002.png)

동아리 질문 게시판에서 발견
-원래 이렇게 되는거면 지워주세영

**Comment by SnowlyFeast** [comment]
이슈 확인

**Comment by SnowlyFeast** [comment]
해결
